### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported (and 22 vulnerabilities) / March 2023 with Node.js v18.14.2

### ISSUE THREAD

**Issue by sheldondotswift** [reck1ess/next-realworld-example-app#41]
\next-realworld-example-app>npm install
npm **WARN** deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm **WARN** deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm **WARN** deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm **WARN** deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm **WARN** deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm **WARN** deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm **WARN** deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm **WARN** deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm **WARN** deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm **WARN** deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

added 787 packages, and audited 788 packages in 10s

40 packages are looking for funding
  run `npm fund` for details

22 vulnerabilities (2 moderate, 13 high, 7 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

\next-realworld-example-app>npm run dev

> next-realworld-example-app@1.0.0 dev
> next dev

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ready - started server on http://localhost:3000
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (\next-realworld-example-app\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (\next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (\next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:471:10)
    at \next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:503:5
    at \next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:358:12
    at \next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (\next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (\next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (\next-realworld-example-app\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (\next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (\next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:471:10)
    at \next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:503:5
    at \next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:358:12
    at \next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (\next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (\next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (\next-realworld-example-app\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (\next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (\next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:471:10)
    at \next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:503:5
    at \next-realworld-example-app\node_modules\webpack\lib\NormalModule.js:358:12
    at \next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (\next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (\next-realworld-example-app\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.2

**Comment by te-ing** [comment]
It's node version issue.
try $ echo 'v16.18.1' > .nvmrc → $ nvm use

**Comment by PavelCp** [comment]
run `npm update` and it resolves issue on node v18.20.2
